version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    docker:
      - image: cimg/base:2022.10
    steps:
      - run: echo "hello world"
  deploy:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: bash ./scripts/github-pages-deploy.sh dist

workflows:
  ci-cd:
    jobs:
      - test
      - deploy
#      - node/run:
#          filters:
#            branches:
#              ignore: gh-pages
#          version: '8.17.0'
#          pkg-manager: yarn
#          yarn-run: build
#      - deploy:
#          requires:
#            - node/run
#          filters:
#            branches:
#              only: circleci-project-setup

#      - node/run:
#          filters:
#            branches:
#              only: master
#          version: '8.17.0'
#          pgk-manager: yarn
#          steps:
#            - checkout
#            - attach_workspace:
#                at: dist
#            - yarn-run: install -g --silent gh-pages@2.0.1
#            - run: Configure git
#              command: |
#                git config user.email "ci@gameoflife.xyz"
#                git config user.name "ci"
#            - run: gh-pages --dist dist






