version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  deploy:
    docker:
      - cimg/base:2022.10
    executor: docker
    steps:
      - checkout
      - run: ./scripts/github-pages-deploy.sh

workflows:
  build/deploy:
    jobs:
      - node/run:
          filters:
            branches:
              ignore: gh-pages
          version: '8.17.0'
          pgk-manager: yarn
          steps:
            - checkout
            - yarn-run: build
            - persist_to_workspace:
                root: .
                paths: dist/*
      - deploy:
          filters:
            branches:
              only: circleci-project-setup

#      - node/run:
#          filters:
#            branches:
#              only: master
#          version: '8.17.0'
#          pgk-manager: yarn
#          steps:
#            - checkout
#            - attach_workspace:
#                at: dist
#            - yarn-run: install -g --silent gh-pages@2.0.1
#            - run: Configure git
#              command: |
#                git config user.email "ci@gameoflife.xyz"
#                git config user.name "ci"
#            - run: gh-pages --dist dist






